
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: FinalProject_development

test:
  <<: *default
  database: FinalProject_test

production:
  <<: *default
  database: FinalProject_production
  username: FinalProject
  password: <%= ENV["FINALPROJECT_DATABASE_PASSWORD"] %>
